services:

  service-a:
    build: ./service-a
    ports:
      - "4001:8080"
    depends_on:
      - service-b
    environment:
      - TAX_SERVICE_URL=http://service-b:4000



  service-b:
    build: ./service-b
    ports:
      - "4002:4000"
